os:
  - linux

sudo: required

install:
  - REMOTE="http://mirror.ctan.org/systems/texlive/tlnet"
  - INSTALL="/tmp/install-texlive"
  - mkdir -p $INSTALL
  - curl -sSL $REMOTE/install-tl-unx.tar.gz | tar -xzv -C $INSTALL --strip-components=1

  - echo "selected_scheme scheme-basic" >> $INSTALL/tl.profile
  - echo "collection-basic 1" >> $INSTALL/tl.profile
  - echo "collection-fontsrecommended 1" >> $INSTALL/tl.profile
  - echo "collection-langchinese 1" >> $INSTALL/tl.profile
  - echo "collection-latex 1" >> $INSTALL/tl.profile
  - echo "collection-latexextra 1" >> $INSTALL/tl.profile
  - echo "collection-latexrecommended 1" >> $INSTALL/tl.profile
  - echo "collection-xetex 1" >> $INSTALL/tl.profile
  - echo "tlpdbopt_autobackup 0" >> $INSTALL/tl.profile
  - echo "tlpdbopt_install_docfiles 0" >> $INSTALL/tl.profile
  - echo "tlpdbopt_install_srcfiles 0" >> $INSTALL/tl.profile

  - sudo $INSTALL/install-tl -profile $INSTALL/tl.profile

  - VERSION=$($INSTALL/install-tl --version | grep 'version' | grep -o '[0-9]\{4\}')
  - PLATFORM=$($INSTALL/install-tl --print-platform)
  - TEXBIN="/usr/local/texlive/${VERSION}/bin/${PLATFORM}"
  - export PATH="$TEXBIN:$PATH"

  - sudo $TEXBIN/tlmgr install algorithm2e latexmk ulem

# English fonts: replace Windows only fonts to TeX default fonts
before_script:
  - sed -i '/setmainfont/d' ustcthesis.dtx
  - sed -i '/setsansfont/d' ustcthesis.dtx
  - sed -i '/setmonofont/d' ustcthesis.dtx

script:
  - make main
  - sed -i 's/doctor/master/' main.tex
  - make main
  - sed -i 's/master/bachelor/' main.tex
  - make main
  - sed -i 's/bachelor/doctor,english/' main.tex
  - make main
  - make doc
